### ISSUE TITLE
'depth' sign_method generates less negative sdf value

### ISSUE THREAD

**Issue by nhk035** [marian42/mesh_to_sdf#20]
Hello, thans for your great job. When I try to generate some points near surface only, negative sdf values was much less than positive(1:10.6). And I plot all sdf values of these points as the follow image(Y axis is sdf value). There is a strange area from -0.001 to 0, which contains little points. Any solution for this?
![image](https://user-images.githubusercontent.com/29883567/106722764-516df480-6641-11eb-97a6-9cb8a2b9e3b4.png)
And my test code is
`points, sdfs = mesh_to_sdf.sample_sdf_near_surface(mesh, sign_method='depth', number_of_points=1000000)`

Thanks!

**Comment by pbsds** [comment]
This issue could perhaps be alleviated with bilinear interpolation in [this](https://github.com/marian42/mesh_to_sdf/blob/master/mesh_to_sdf/scan.py#L106) function.

**Comment by nhk035** [comment]
Sorry for late reply. @pbsds 
I checked the code and found that these points are generated by adding the gaussian noise to surface points. Therefore, these near points should be 1:1 on each side of the surface in theroy instead of 1:10 as I posted. 
Furthermore, interpolation maybe a valid solution, but how can i make sure points localed betewwn -0.001 and 0 are not wrongly counted to a positive interval?
Thans a lot!

**Comment by pbsds** [comment]
The surface points are pertubed with noise, the distance is is calculated with a nearest neighboring surface point search, then the sign is determined with a depth check.
The depth check is done from 50 random camera perspectives. If the point is visible from at **least one** of these camera then it is counted as being on the outside. With great artistic skill i mocked together a diagram, of a step-line (nearest neightbor) and a linearly interpreted line:

![image](https://user-images.githubusercontent.com/140964/113144241-5314fc80-922d-11eb-8a2e-c08f1f1a0556.png)

The blue circle is from this camera perspective erroneously counted as being on the outside, while the red one is counted as being on the inside. The red one will likely be be put on the outside from a different perspective, but the blue one is where the issue lies.

**Comment by nhk035** [comment]
Thanks for your great diagram ^v^!
As I understand, the step line means the depth I got [here](https://github.com/marian42/mesh_to_sdf/blob/66036a747e82e7129f6afc74c5325d676a322114/mesh_to_sdf/scan.py#L114)  whitch is not the real depth of the surface point corresponding to current query point. Am I right?

**Comment by pbsds** [comment]
I believe so. The `.astype(int)` is where the rounding happens.
